config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/card-sorts', to: 'pages#card_sorts', as: 'card_sorts_page'
  get '/tree-tests', to: 'pages#tree_tests', as: 'tree_tests_page'
  get '/pricing', to: 'pages#pricing'

  get '/dashboard', to: 'dashboard#show', as: 'dashboard'
  get '/verify', to: 'dashboard#verify', as: 'verify'
  get '/reverify', to: 'dashboard#reverify', as: 'reverify'

  get '/account', to: 'account#show', as: 'account'
  post '/update-email', to: 'account#update_email', as: 'update_email'
  post '/change-password', to: 'account#change_password', as: 'change_password'
  post '/delete_account', to: 'account#delete_account', as: 'delete_account'
  
  get '/godview', to: 'dashboard#godview'

  get '/500', to: 'errors#server_error'
  get '/422', to: 'errors#unacceptable'
  get '/404', to: 'errors#not_found', as: 'not_found'

  get '/signup', to: 'authentication#new_signup', as: 'signup'
  post '/signup', to: 'authentication#signup', as: 'signup_post'
  get '/login', to: 'authentication#new_login', as: 'login'
  post '/login', to: 'authentication#login', as: 'login_post'
  delete '/logout', to: 'authentication#logout', as: 'logout'
  get '/reset-password', to: 'authentication#new_reset_password', as: 'reset_password'
  post '/reset-password', to: 'authentication#reset_password', as: 'reset_password_post'
  get '/set-password/:token', to: 'authentication#new_set_password', as: 'set_password'
  post '/set-password', to: 'authentication#set_password', as: 'set_password_post'

  get '/email_verification/:token', to: 'email_verification#verify', as: 'email_verification'

  resources :tree_tests do
    get 'report', on: :member
    get 'participants', on: :member
  end

  resources :tree_test_tasks do
    get 'outcome', on: :member
  end

  resources :tree_test_participants
  
  resources :card_sorts do 
    get 'report', on: :member
  end
  
  resources :card_sort_groups
  post '/participant_designated_card_sort_groups', to: 'card_sort_groups#create_participant_designated_group'
  post '/merge_groups', to: 'card_sort_groups#merge_groups'
  post '/unmerge_groups', to: 'card_sort_groups#unmerge_groups'
  post '/update_merged_group', to: 'card_sort_groups#update_merged_group'

  resources :card_sort_cards
  
  resources :card_sort_participants

  post '/subscription/new', to: 'subscription#new'
  post '/subscription/create', to: 'subscription#create'

  get 'collect_tt/:auth_token', to: 'tree_test_participants#new', as: :tree_test_collect
  get 'collect_tt/:auth_token/:preview', to: 'tree_test_participants#new', as: :tree_test_collect_preview

  get 'collect_cs/:auth_token', to: 'card_sort_participants#new', as: :card_sort_collect
  get 'collect_cs/:auth_token/:preview', to: 'card_sort_participants#new', as: :card_sort_collect_preview  


  resources :tree_test_reports, only: :show do
    member do 
      get 'login'
      post 'login'
    end
  end

  resources :card_sort_reports, only: :show do
    member do 
      get 'login'
      post 'login'
    end
  end

  get '/admin/password_reset', to: 'admin#password_reset'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_before_action :check_verification, only: [:verify, :reverify]
  layout 'dashboard'

  def show 
    cookies.delete :actioncable_user_id   
    @card_sorts = current_user.card_sorts.group(:status).count
    @tree_tests = current_user.tree_tests.group(:status).count
  end

  def verify
    if current_user.verified
      redirect_to dashboard_path
    else 
      cookies.encrypted[:actioncable_user_id] = current_user.id
    end
  end

  def reverify
    current_user.email_verifications.create unless current_user.verified
    redirect_to dashboard_path
  end
end

app/views/dashboard/godview.html.erb
<main class="py-6">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <h1 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate mb-6">God View</h1>
  </div>
  <div class="w-full lg:max-w-7xl lg:mx-auto lg:px-8">
    <div class="mb-6">
      <div class="sm:hidden">
        <select aria-label="Selected tab" class="form-select block w-full">
          <option selected>Active</option>
          <option>Canceled</option>
          <option>Tirekicker</option>
        </select>
      </div>
      <div class="hidden sm:block">
        <nav class="flex">
          <a href="#" class="px-3 py-2 font-medium text-sm leading-5 rounded-md text-purple-700 bg-purple-100 focus:outline-none focus:text-purple-800 focus:bg-purple-200" aria-current="page">
            Active
          </a>
          <a href="#" class="ml-4 px-3 py-2 font-medium text-sm leading-5 rounded-md text-gray-500 hover:text-gray-700 focus:outline-none focus:text-purple-600 focus:bg-purple-50">
            Canceled
          </a>
          <a href="#" class="ml-4 px-3 py-2 font-medium text-sm leading-5 rounded-md text-gray-500 hover:text-gray-700 focus:outline-none focus:text-purple-600 focus:bg-purple-50">
            Tirekicker
          </a>
        </nav>
      </div>
    </div>
    <div class="flex flex-col">
      <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
          <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
            <table class="min-w-full divide-y divide-gray-200">
              <thead>
                <tr>
                  <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                    Account
                  </th>
                  <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                    Type
                  </th>
                  <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                    Created
                  </th>
                  <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                    Subscription
                  </th>
                  <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                    LTV
                  </th>
                  <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                    Users
                  </th>
                  <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                    Drafts
                  </th>
                  <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                    Published
                  </th>
                  <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                    Masquerade
                  </th>
                </tr>
              </thead>
              <tbody class="bg-white divide-y divide-gray-200">
                <tr>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900">
                    John Smith
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    Solo
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    01/01/21
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    Annual
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    948
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    1
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    3
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    1
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
                    <a href="#" class="text-purple-600 hover:text-purple-900">login</a>
                  </td>
                </tr>
                <tr>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900">
                    Sallie Jones
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    Solo
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    09/30/20
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    Monthly
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    99
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    1
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    1
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    0
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
                    <a href="#" class="text-purple-600 hover:text-purple-900">login</a>
                  </td>
                </tr>
                <tr>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900">
                    Brave UX
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    Agency
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    01/13/21
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    Annual
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    2388
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    3
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    3
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    1
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
                    <a href="#" class="text-purple-600 hover:text-purple-900">login</a>
                  </td>
                </tr>
                <tr>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900">
                    Disney Parks, Experiences and Products, Inc.
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    Team
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    01/13/21
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    Annual
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    2388
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    3
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    3
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    1
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
                    <a href="#" class="text-purple-600 hover:text-purple-900">login</a>
                  </td>
                </tr>
              </tbody>
            </table>
            <nav class="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6">
            <div class="hidden sm:block">
              <p class="text-sm leading-5 text-gray-700">
                Showing
                <span class="font-medium">1</span>
                to
                <span class="font-medium">10</span>
                of
                <span class="font-medium">20</span>
                results
              </p>
            </div>
            <div class="flex-1 flex justify-between sm:justify-end">
              <a href="#" class="relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm leading-5 font-medium rounded-md text-gray-700 bg-white hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:bg-gray-100 active:text-gray-700 transition ease-in-out duration-150">
                Previous
              </a>
              <a href="#" class="ml-3 relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm leading-5 font-medium rounded-md text-gray-700 bg-white hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:bg-gray-100 active:text-gray-700 transition ease-in-out duration-150">
                Next
              </a>
            </div>
          </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/dashboard/show.html.erb
<div class="py-6 border-b">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="md:flex md:items-center md:justify-between">
      <div class="flex-1 min-w-0">
        <h1 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
          Dashboard
        </h1>
      </div>
    </div>
  </div>
</div>
<main class="py-6">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <h2 class="mb-6 text-gray-500 text-xs font-medium uppercase tracking-wide">Research Studies</h2>
    <div class="mt-3 grid grid-cols-1 gap-5 sm:gap-6 lg:grid-cols-3">
      <%= link_to card_sorts_path, {class: "focus:outline-none"} do %>
        <div class="col-span-1 flex-grow rounded-md bg-white shadow">
          <div class="px-4 py-5 sm:p-6">
            <h3 class="text-lg leading-6 font-medium text-purple-600">
              Card Sorts
            </h3>
            <div class="mt-2 max-w-xl text-xs leading-5 text-gray-500">
              <div class="inline">
                Published
                <span class="inline-flex items-center px-3 py-0.5 rounded-full font-medium leading-5 bg-green-100 text-green-800">
                  <%= @card_sorts['published'] || 0 %>
                </span>
              </div>
              <div class="inline ml-2">
                Drafts
                <span class="inline-flex items-center px-3 py-0.5 rounded-full font-medium leading-5 bg-orange-100 text-orange-800">
                  <%= @card_sorts['draft'] || 0 %>
                </span>
              </div>
              <div class="inline ml-2">
                Ended
                <span class="inline-flex items-center px-3 py-0.5 rounded-full font-medium leading-5 bg-gray-100 text-gray-800">
                  <%= @card_sorts['ended'] || 0 %>
                </span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to tree_tests_path, {class: "focus:outline-none"} do %>
        <div class="col-span-1 flex-grow rounded-md bg-white shadow">
          <div class="px-4 py-5 sm:p-6">
            <h3 class="text-lg leading-6 font-medium text-purple-600">
              Tree Tests
            </h3>
            <div class="mt-2 max-w-xl text-xs leading-5 text-gray-500">
              <div class="inline">
                Published
                <span class="inline-flex items-center px-3 py-0.5 rounded-full font-medium leading-5 bg-green-100 text-green-800">
                  <%= @tree_tests['published'] || 0 %>
                </span>
              </div>
              <div class="inline ml-2">
                Drafts
                <span class="inline-flex items-center px-3 py-0.5 rounded-full font-medium leading-5 bg-orange-100 text-orange-800">
                  <%= @tree_tests['draft'] || 0 %>
                </span>
              </div>
              <div class="inline ml-2">
                Ended
                <span class="inline-flex items-center px-3 py-0.5 rounded-full font-medium leading-5 bg-gray-100 text-gray-800">
                  <%= @tree_tests['ended'] || 0 %>
                </span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <div class="col-span-1 flex-grow rounded-md bg-white shadow">
        <div class="px-4 py-5 sm:p-6">
          <h3 class="text-lg leading-6 font-medium text-gray-500">
            More UX Tools on the way!
          </h3>
          <div class="mt-2 max-w-xl text-xs leading-5 text-gray-500">
            <a href="mailto:support@uxmetrics.com" class="font-medium text-purple-600 hover:text-purple-500 transition ease-in-out duration-150">
              Tell us what should we ship next &rarr;
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/dashboard/verify.html.erb
<% content_for :page_title, "Create your #{Rails.configuration.application_name} account." %>
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full">
    <div>
      <%= link_to image_tag(asset_pack_path("media/images/uxmetrics-logo.svg"), size: "39x39", class: "mx-auto h-12 w-auto"), root_path, class: "" %>
      <h2 class="mt-6 text-center text-3xl leading-9 font-extrabold text-gray-900">
        Please check your email
      </h2>
      <p class="mt-2 text-center text-sm leading-5 text-gray-600">
        We sent a verification link to <%= current_user.email %>. Please click the link to finish creating your account. Didn't receive it? Check your promotions or spam folder, or <a href="<%= reverify_path %>" class="font-medium text-purple-600 hover:text-purple-500 transition ease-in-out duration-150">request a new one</a>.
      </p>
    </div>
  </div>
</div>