config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/card-sorts', to: 'pages#card_sorts', as: 'card_sorts_page'
  get '/tree-tests', to: 'pages#tree_tests', as: 'tree_tests_page'
  get '/pricing', to: 'pages#pricing'

  get '/dashboard', to: 'dashboard#show', as: 'dashboard'
  get '/verify', to: 'dashboard#verify', as: 'verify'
  get '/reverify', to: 'dashboard#reverify', as: 'reverify'

  get '/account', to: 'account#show', as: 'account'
  post '/update-email', to: 'account#update_email', as: 'update_email'
  post '/change-password', to: 'account#change_password', as: 'change_password'
  post '/delete_account', to: 'account#delete_account', as: 'delete_account'
  
  get '/godview', to: 'dashboard#godview'

  get '/500', to: 'errors#server_error'
  get '/422', to: 'errors#unacceptable'
  get '/404', to: 'errors#not_found', as: 'not_found'

  get '/signup', to: 'authentication#new_signup', as: 'signup'
  post '/signup', to: 'authentication#signup', as: 'signup_post'
  get '/login', to: 'authentication#new_login', as: 'login'
  post '/login', to: 'authentication#login', as: 'login_post'
  delete '/logout', to: 'authentication#logout', as: 'logout'
  get '/reset-password', to: 'authentication#new_reset_password', as: 'reset_password'
  post '/reset-password', to: 'authentication#reset_password', as: 'reset_password_post'
  get '/set-password/:token', to: 'authentication#new_set_password', as: 'set_password'
  post '/set-password', to: 'authentication#set_password', as: 'set_password_post'

  get '/email_verification/:token', to: 'email_verification#verify', as: 'email_verification'

  resources :tree_tests do
    get 'report', on: :member
    get 'participants', on: :member
  end

  resources :tree_test_tasks do
    get 'outcome', on: :member
  end

  resources :tree_test_participants
  
  resources :card_sorts do 
    get 'report', on: :member
  end
  
  resources :card_sort_groups
  post '/participant_designated_card_sort_groups', to: 'card_sort_groups#create_participant_designated_group'
  post '/merge_groups', to: 'card_sort_groups#merge_groups'
  post '/unmerge_groups', to: 'card_sort_groups#unmerge_groups'
  post '/update_merged_group', to: 'card_sort_groups#update_merged_group'

  resources :card_sort_cards
  
  resources :card_sort_participants

  post '/subscription/new', to: 'subscription#new'
  post '/subscription/create', to: 'subscription#create'

  get 'collect_tt/:auth_token', to: 'tree_test_participants#new', as: :tree_test_collect
  get 'collect_tt/:auth_token/:preview', to: 'tree_test_participants#new', as: :tree_test_collect_preview

  get 'collect_cs/:auth_token', to: 'card_sort_participants#new', as: :card_sort_collect
  get 'collect_cs/:auth_token/:preview', to: 'card_sort_participants#new', as: :card_sort_collect_preview  


  resources :tree_test_reports, only: :show do
    member do 
      get 'login'
      post 'login'
    end
  end

  resources :card_sort_reports, only: :show do
    member do 
      get 'login'
      post 'login'
    end
  end

  get '/admin/password_reset', to: 'admin#password_reset'
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div 
    x-data="{ show: false}" 
    x-show="show" 
    x-init="() => { show = true; setTimeout(function(){ show = false }, 5000) }" 
    class="fixed inset-x-0 bottom-0"
    x-transition:enter="transition ease-linear duration-500"
    x-transition:enter-start="transform translate-y-full"
    x-transition:enter-end="transform -translate-y-0"
    x-transition:leave="transition ease-linear duration-500"
    x-transition:leave-start="transform -translate-y-0"
    x-transition:leave-end="transform translate-y-full"  
  >
    <div class="relative bg-black opacity-75">
      <div class="max-w-screen-xl mx-auto py-6 px-3 sm:px-6 lg:px-8">
        <div class="pr-16 sm:text-center sm:px-16">
          <p class="font-medium text-white">
            <span class="md:inline">
              <%= flash[:notice] %>
            </span>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-gray-800">
  <div class="max-w-screen-xl mx-auto py-12 px-4 overflow-hidden sm:px-6 lg:px-8">
    <nav class="-mx-5 -my-2 flex flex-wrap justify-center">
      <div class="px-5 py-2">
        <a href="/" class="text-base leading-6 text-gray-300 hover:text-white">
          Home
        </a>
      </div>
      <div class="px-5 py-2">
        <%= link_to "Card Sorts", card_sorts_page_path, class: "text-base leading-6 text-gray-300 hover:text-white" %>
      </div>
      <div class="px-5 py-2">
        <%= link_to "Tree Tests", tree_tests_page_path, class: "text-base leading-6 text-gray-300 hover:text-white" %>
      </div>      
      <div class="px-5 py-2">
        <%= link_to "Pricing", pricing_path, class: "text-base leading-6 text-gray-300 hover:text-white" %>
      </div>
      <div class="px-5 py-2">
        <%= link_to "Sign Up", signup_path, class: "text-base leading-6 text-gray-300 hover:text-white" %>
      </div>
      <div class="px-5 py-2">
        <%= link_to "Login", login_path, class: "text-base leading-6 text-gray-300 hover:text-white" %>
      </div>
    </nav>
    <div class="mt-8">
      <p class="mb-4 text-center text-base leading-6 text-gray-400">
        &copy; 2020-<%= Time.zone.now.strftime("%Y") %> UX Metrics, LLC. All rights reserved.
      </p>
      <p class="mb-4 text-center text-sm leading-5 text-gray-400">
        <a href="https://app.termly.io/document/terms-of-use-for-saas/400a928b-a533-43e0-b5c0-204b554112e7" class="text-gray-400" target="blank">Terms of Use</a> <a href="https://app.termly.io/document/privacy-policy/19f125db-4626-468f-836d-8312d177cded" class="ml-4 text-gray-400" target="blank">Privacy Policy</a></p>
      </p>
      <p class="mb-4 text-center text-sm leading-5 text-gray-400">
        Made in Seattle with 🌲 and Albuquerque with 🌶️
      </p>
      <p class="text-center">
        <button class="termly-cookie-preference-button" type="button" style="background: white; width: 165px; height: 30px; border-radius: 3px; border: 1px solid #5f7d9c; font-family: Roboto, Arial; font-size: 10px; color: #5f7d9c; font-weight: 600; box-sizing: border-box; cursor: pointer; padding: 0; outline: none;" onclick="displayPreferenceModal()">Manage Cookie Preferences</button>
      </p>
    </div>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<nav x-data="{ open: false }" class="bg-white shadow-sm">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between h-16">
      <div class="flex">
        <div class="flex-shrink-0 flex items-center">
          <%= link_to image_tag(asset_pack_path("media/images/uxmetrics-logo-full.svg"), size: "163x40"), root_path, class: "block lg:hidden" %>
          <%= link_to image_tag(asset_pack_path("media/images/uxmetrics-logo-full.svg"), size: "163x40"), root_path, class: "hidden lg:block" %>
        </div>
        <div class="hidden md:ml-6 md:flex">
          <%= link_to "Card Sorts", card_sorts_page_path, class:"inline-flex items-center px-1 pt-1 text-sm font-medium leading-5 text-gray-900 focus:outline-none focus:border-purple-700 transition duration-150 ease-in-out" %>
        </div>
        <div class="hidden md:ml-6 md:flex">
          <%= link_to "Tree Tests", tree_tests_page_path, class:"inline-flex items-center px-1 pt-1 text-sm font-medium leading-5 text-gray-900 focus:outline-none focus:border-purple-700 transition duration-150 ease-in-out" %>
        </div>
        <div class="hidden md:ml-6 md:flex">
          <%= link_to "Pricing", pricing_path, class:"inline-flex items-center px-1 pt-1 text-sm font-medium leading-5 text-gray-900 focus:outline-none focus:border-purple-700 transition duration-150 ease-in-out" %>
        </div>
      </div>
      <div class="hidden md:ml-6 sm:flex sm:items-center">
        <div class="ml-3 relative">
          <div>
            <div class="hidden md:ml-6 md:flex md:items-center">
              <span class="inline-flex rounded-md shadow-md mr-4">
                <span class="inline-flex rounded-md shadow-xs">
                  <%= link_to "Log in", login_path, class: "inline-flex items-center px-4 py-2 border border-transparent text-base leading-6 font-medium rounded-md text-purple-600 bg-white hover:bg-gray-50 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out" %>
                </span>
              </span>
              <span class="inline-flex rounded-md shadow-md">
                <span class="inline-flex rounded-md shadow-xs">
                  <%= link_to "Sign up", signup_path, class: "inline-flex items-center px-4 py-2 border border-transparent text-base leading-6 font-medium rounded-md text-white text-white bg-purple-600 hover:bg-purple-500 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out" %>
                </span>
              </span>
            </div>
          </div>
        </div>
      </div>
      <div class="-mr-2 flex items-center md:hidden">
        <button @click="open = !open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
          <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
            <path :class="{'hidden': open, 'inline-flex': !open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            <path :class="{'hidden': !open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>
  <div :class="{'block': open, 'hidden': !open}" class="hidden sm:hidden">
    <div class="pt-2 pb-3">
      <%= link_to "Card Sorts", card_sorts_page_path, class:"mt-1 block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:outline-none focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300 transition duration-150 ease-in-out"%>
      <%= link_to "Tree Tests", tree_tests_page_path, class:"mt-1 block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:outline-none focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300 transition duration-150 ease-in-out"%>
      <%= link_to "Pricing", pricing_path, class:"mt-1 block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:outline-none focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300 transition duration-150 ease-in-out"%>
    </div>
    <div class="pt-4 pb-3 border-t border-gray-200">
      <%= link_to "Log in", login_path, class: "mt-1 block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100 focus:outline-none focus:text-gray-800 focus:bg-gray-100 transition duration-150 ease-in-out" %>
      <%= link_to "Sign up", signup_path, class: "mt-1 block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100 focus:outline-none focus:text-gray-800 focus:bg-gray-100 transition duration-150 ease-in-out" %>
    </div>
  </div>
</nav>