config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/card-sorts', to: 'pages#card_sorts', as: 'card_sorts_page'
  get '/tree-tests', to: 'pages#tree_tests', as: 'tree_tests_page'
  get '/pricing', to: 'pages#pricing'

  get '/dashboard', to: 'dashboard#show', as: 'dashboard'
  get '/verify', to: 'dashboard#verify', as: 'verify'
  get '/reverify', to: 'dashboard#reverify', as: 'reverify'

  get '/account', to: 'account#show', as: 'account'
  post '/update-email', to: 'account#update_email', as: 'update_email'
  post '/change-password', to: 'account#change_password', as: 'change_password'
  post '/delete_account', to: 'account#delete_account', as: 'delete_account'
  
  get '/godview', to: 'dashboard#godview'

  get '/500', to: 'errors#server_error'
  get '/422', to: 'errors#unacceptable'
  get '/404', to: 'errors#not_found', as: 'not_found'

  get '/signup', to: 'authentication#new_signup', as: 'signup'
  post '/signup', to: 'authentication#signup', as: 'signup_post'
  get '/login', to: 'authentication#new_login', as: 'login'
  post '/login', to: 'authentication#login', as: 'login_post'
  delete '/logout', to: 'authentication#logout', as: 'logout'
  get '/reset-password', to: 'authentication#new_reset_password', as: 'reset_password'
  post '/reset-password', to: 'authentication#reset_password', as: 'reset_password_post'
  get '/set-password/:token', to: 'authentication#new_set_password', as: 'set_password'
  post '/set-password', to: 'authentication#set_password', as: 'set_password_post'

  get '/email_verification/:token', to: 'email_verification#verify', as: 'email_verification'

  resources :tree_tests do
    get 'report', on: :member
    get 'participants', on: :member
  end

  resources :tree_test_tasks do
    get 'outcome', on: :member
  end

  resources :tree_test_participants
  
  resources :card_sorts do 
    get 'report', on: :member
  end
  
  resources :card_sort_groups
  post '/participant_designated_card_sort_groups', to: 'card_sort_groups#create_participant_designated_group'
  post '/merge_groups', to: 'card_sort_groups#merge_groups'
  post '/unmerge_groups', to: 'card_sort_groups#unmerge_groups'
  post '/update_merged_group', to: 'card_sort_groups#update_merged_group'

  resources :card_sort_cards
  
  resources :card_sort_participants

  post '/subscription/new', to: 'subscription#new'
  post '/subscription/create', to: 'subscription#create'

  get 'collect_tt/:auth_token', to: 'tree_test_participants#new', as: :tree_test_collect
  get 'collect_tt/:auth_token/:preview', to: 'tree_test_participants#new', as: :tree_test_collect_preview

  get 'collect_cs/:auth_token', to: 'card_sort_participants#new', as: :card_sort_collect
  get 'collect_cs/:auth_token/:preview', to: 'card_sort_participants#new', as: :card_sort_collect_preview  


  resources :tree_test_reports, only: :show do
    member do 
      get 'login'
      post 'login'
    end
  end

  resources :card_sort_reports, only: :show do
    member do 
      get 'login'
      post 'login'
    end
  end

  get '/admin/password_reset', to: 'admin#password_reset'
end

app/controllers/authentication_controller.rb
class AuthenticationController < UnauthenticatedController
  layout 'authentication'
  before_action :check_for_login, except: :logout

  def signup        
    user = User.create(email: params[:email], password: params[:password])
    user.email_verifications.create
    login_user(user)    
    redirect_to dashboard_path

  rescue ActiveRecord::RecordNotUnique
    redirect_to signup_path, notice: 'Unable to create account.'
  end

  def login
    if user = User.find_by(email: params[:email]).try(:authenticate, params[:password])
      login_user(user)
      remember_user(user) if (params[:remember_me] == 1)
      redirect_to dashboard_path, notice: 'Successfully logged in.'
    else
      redirect_to login_path, notice: 'Unable to log in.'
    end
  end

  def logout
    cookies.delete :user_id
    reset_session
    redirect_to root_path, notice: 'You have logged out.'
  end

  def reset_password
    User.find_by(email: params[:email]).password_resets.create
    redirect_to reset_password_path, notice: 'You will receive an email with instructions for how to unlock your account in a few minutes.'
  end

  def new_set_password
    if password_reset = PasswordReset.find_by(token: params[:token])
      if password_reset.created_at > 1.day.ago
        @temp_password = SecureRandom.hex(32)
        @user_id = password_reset.user.id
        password_reset.user.update(password: @temp_password)
        password_reset.destroy
      else 
        password_reset.user.password_resets.create
        password_reset.destroy
        redirect_to root_path, notice: 'Expired password reset. Please check your email for a new one.'
      end
    else
      redirect_to reset_password_path, notice: 'Invalid password reset link.'
    end
  end

  def set_password
    if user = User.find(params[:id]).authenticate(params[:reset_password_token])
      user.update(password: params[:password])
      redirect_to login_path, notice: 'Password reset. Please log in.'
    else
      redirect_to reset_password_path, notice: 'Unable to reset password.'
    end
  end

  private

  def login_user(user)
    reset_session
    session[:user_id] = user.id
  end

  def remember_user(user)
    cookies.encrypted[:user_id] = user.id
  end

  def check_for_login
    redirect_to dashboard_path if (session[:user_id] || cookies.encrypted[:user_id])
  end

end

app/views/authentication/new_login.html.erb
<% content_for :page_title, "Log in to #{Rails.configuration.application_name}" %>
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full">
    <div>
      <%= link_to image_tag(asset_pack_path("media/images/uxmetrics-logo.svg"), size: "39x39", class: "mx-auto h-12 w-auto"), root_path, class: "" %>
      <h2 class="mt-6 text-center text-3xl leading-9 font-extrabold text-gray-900">
        Log in to your account
      </h2>
      <p class="mt-2 text-center text-sm leading-5 text-gray-600">
        Or
        <%= link_to "sign up for free", signup_path, class: "font-medium text-purple-600 hover:text-purple-500 focus:outline-none focus:underline transition ease-in-out duration-150"%>
      </p>
    </div>
    <%= form_with url: login_path, method: 'post', local: true, class: 'mt-8' do |form| %>
      <div class="rounded-md shadow-sm">
        <div>
          <%= form.email_field :email, autocomplete: "email", class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:shadow-outline-blue focus:border-blue-300 focus:z-10 sm:text-sm sm:leading-5", 'aria-label' => 'Email address', placeholder: 'Email address' %>
        </div>
        <div class="-mt-px">
          <%= form.password_field :password, autocomplete: "current-password", class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:shadow-outline-blue focus:border-blue-300 focus:z-10 sm:text-sm sm:leading-5", 'aria-label' => 'Password', placeholder: 'Password' %>
        </div>
      </div>

      <div class="mt-6 flex items-center justify-between">
        <div class="flex items-center">
          <%= form.check_box :remember_me, class: "form-checkbox h-4 w-4 text-purple-600 transition duration-150 ease-in-out" %>
          <%= form.label :remember_me, 'Remember me', class: 'ml-2 block text-sm leading-5 text-gray-900' %>
        </div>

        <div class="text-sm leading-5">
          <%= link_to "Forgot your password?", reset_password_path, class: "font-medium text-purple-600 hover:text-purple-500 focus:outline-none focus:underline transition ease-in-out duration-150" %>
        </div>
      </div>

      <div class="mt-6">
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-purple-600 hover:bg-purple-500 focus:outline-none focus:border-purple-700 focus:shadow-outline-purple active:bg-purple-700 transition duration-150 ease-in-out">
          <span class="absolute left-0 inset-y-0 flex items-center pl-3">
            <svg class="h-5 w-5 text-purple-500 group-hover:text-purple-400 transition ease-in-out duration-150" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
            </svg>
          </span>
          Log In
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/authentication/new_reset_password.html.erb
<% content_for :page_title, "Reset your #{Rails.configuration.application_name} password" %>
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full">
    <div>
      <%= link_to image_tag(asset_pack_path("media/images/uxmetrics-logo.svg"), size: "39x39", class: "mx-auto h-12 w-auto"), root_path, class: "" %>
      <h2 class="mt-6 text-center text-3xl leading-9 font-extrabold text-gray-900">
        Reset your password
      </h2>
      <p class="mt-2 text-center text-sm leading-5 text-gray-600">
        Or
        <%= link_to "Log in", login_path, class: "font-medium text-purple-600 hover:text-purple-500 focus:outline-none focus:underline transition ease-in-out duration-150" %>
      </p>
    </div>
    <%= form_with url: reset_password_post_path, method: 'post', local: true, class: "mt-8" do |form| %>
      <div class="rounded-md shadow-sm">
        <div>
          <%= form.email_field :email, autocomplete: "email", class: "appearance-none rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 focus:z-10 sm:text-sm sm:leading-5", 'aria-label' => 'Email address', placeholder: 'Email address' %>
        </div>
      </div>

      <div class="mt-6">
        <%= form.submit "Reset Password", class: "cursor-pointer w-full flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-purple-600 hover:bg-purple-500 focus:outline-none focus:border-purple-700 focus:shadow-outline-purple active:bg-purple-700 transition duration-150 ease-in-out" %>
      </div>
    <% end %>
  </div>
</div>

app/views/authentication/new_set_password.html.erb
<% content_for :page_title, "Log in to #{Rails.configuration.application_name}" %>
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full">
    <div>
      <%= link_to image_tag(asset_pack_path("media/images/uxmetrics-logo.svg"), size: "39x39", class: "mx-auto h-12 w-auto"), root_path, class: "" %>
      <h2 class="mt-6 text-center text-3xl leading-9 font-extrabold text-gray-900">
        Create a new password
      </h2>
      <p class="mt-2 text-center text-sm leading-5 text-gray-600">
        Or
        <%= link_to "Log in", login_path, class: "font-medium text-purple-600 hover:text-purple-500 focus:outline-none focus:underline transition ease-in-out duration-150" %>
      </p>
    </div>
    <%= form_with url: set_password_post_path, method: 'post', local: true, class: "mt-8" do |form| %>
      <%= form.hidden_field :reset_password_token, value: @temp_password %>
      <%= form.hidden_field :id, value: @user_id %>
      <div class="rounded-md shadow-sm">
        <div>
          <%= form.password_field :password, autofocus: true, autocomplete: "new-password", class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:shadow-outline-blue focus:border-blue-300 focus:z-10 sm:text-sm sm:leading-5", 'aria-label' => 'Password', placeholder: 'New Password' %>
        </div>
      </div>

      <div class="mt-6">
        <%= form.submit "Save New Password", class: "cursor-pointer w-full flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-purple-600 hover:bg-purple-500 focus:outline-none focus:border-purple-700 focus:shadow-outline-purple active:bg-purple-700 transition duration-150 ease-in-out" %>
      </div>
    <% end %>
  </div>
</div>

app/views/authentication/new_signup.html.erb
<% content_for :page_title, "Create your #{Rails.configuration.application_name} account." %>
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full">
    <div>
      <%= link_to image_tag(asset_pack_path("media/images/uxmetrics-logo.svg"), size: "39x39", class: "mx-auto h-12 w-auto"), root_path, class: "" %>
      <h2 class="mt-6 text-center text-3xl leading-9 font-extrabold text-gray-900">
        Create your account
      </h2>
      <p class="mt-2 text-center text-sm leading-5 text-gray-600">
        Or
        <%= link_to "Log in", login_path, class: "font-medium text-purple-600 hover:text-purple-500 focus:outline-none focus:underline transition ease-in-out duration-150" %>
      </p>
    </div>
    <%= form_with url: signup_post_path, method: 'post', local: true, class: "mt-8" do |form| %>
      <div class="rounded-md shadow-sm">
        <div>
          <%= form.email_field :email, placeholder: "Email address", autocomplete: "email", required: true, class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:shadow-outline-blue focus:border-blue-300 focus:z-10 sm:text-sm sm:leading-5", 'aria-label' => 'Email address' %>
        </div>
        <div class="-mt-px">
          <%= form.password_field :password, placeholder: "Password", autocomplete: "new-password", required: true, class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:shadow-outline-blue focus:border-blue-300 focus:z-10 sm:text-sm sm:leading-5", 'aria-label' => 'Password' %>
        </div>
      </div>

      <div class="mt-6 flex items-center justify-between">
        <div class="flex items-center">
          <input id="consent" required type="checkbox" class="form-checkbox h-4 w-4 text-purple-600 transition duration-150 ease-in-out">
          <label for="consent" class="ml-2 block text-sm leading-5 text-gray-900">
            I agree to the <a href="https://app.termly.io/document/terms-of-use-for-saas/400a928b-a533-43e0-b5c0-204b554112e7" class="font-medium text-purple-600 hover:text-purple-500 focus:outline-none focus:underline transition ease-in-out duration-150" target="blank">Terms Of Use</a> and <a href="https://app.termly.io/document/privacy-policy/19f125db-4626-468f-836d-8312d177cded" class="font-medium text-purple-600 hover:text-purple-500 focus:outline-none focus:underline transition ease-in-out duration-150" target="blank">Privacy Policy</a>.
          </label>
        </div>
      </div>

      <div class="mt-6">
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-purple-600 hover:bg-purple-500 focus:outline-none focus:border-purple-700 focus:shadow-outline-purple active:bg-purple-700 transition duration-150 ease-in-out">
          Create Account
        </button>
      </div>
    <% end %>
  </div>
</div>