config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/card-sorts', to: 'pages#card_sorts', as: 'card_sorts_page'
  get '/tree-tests', to: 'pages#tree_tests', as: 'tree_tests_page'
  get '/pricing', to: 'pages#pricing'

  get '/dashboard', to: 'dashboard#show', as: 'dashboard'
  get '/verify', to: 'dashboard#verify', as: 'verify'
  get '/reverify', to: 'dashboard#reverify', as: 'reverify'

  get '/account', to: 'account#show', as: 'account'
  post '/update-email', to: 'account#update_email', as: 'update_email'
  post '/change-password', to: 'account#change_password', as: 'change_password'
  post '/delete_account', to: 'account#delete_account', as: 'delete_account'
  
  get '/godview', to: 'dashboard#godview'

  get '/500', to: 'errors#server_error'
  get '/422', to: 'errors#unacceptable'
  get '/404', to: 'errors#not_found', as: 'not_found'

  get '/signup', to: 'authentication#new_signup', as: 'signup'
  post '/signup', to: 'authentication#signup', as: 'signup_post'
  get '/login', to: 'authentication#new_login', as: 'login'
  post '/login', to: 'authentication#login', as: 'login_post'
  delete '/logout', to: 'authentication#logout', as: 'logout'
  get '/reset-password', to: 'authentication#new_reset_password', as: 'reset_password'
  post '/reset-password', to: 'authentication#reset_password', as: 'reset_password_post'
  get '/set-password/:token', to: 'authentication#new_set_password', as: 'set_password'
  post '/set-password', to: 'authentication#set_password', as: 'set_password_post'

  get '/email_verification/:token', to: 'email_verification#verify', as: 'email_verification'

  resources :tree_tests do
    get 'report', on: :member
    get 'participants', on: :member
  end

  resources :tree_test_tasks do
    get 'outcome', on: :member
  end

  resources :tree_test_participants
  
  resources :card_sorts do 
    get 'report', on: :member
  end
  
  resources :card_sort_groups
  post '/participant_designated_card_sort_groups', to: 'card_sort_groups#create_participant_designated_group'
  post '/merge_groups', to: 'card_sort_groups#merge_groups'
  post '/unmerge_groups', to: 'card_sort_groups#unmerge_groups'
  post '/update_merged_group', to: 'card_sort_groups#update_merged_group'

  resources :card_sort_cards
  
  resources :card_sort_participants

  post '/subscription/new', to: 'subscription#new'
  post '/subscription/create', to: 'subscription#create'

  get 'collect_tt/:auth_token', to: 'tree_test_participants#new', as: :tree_test_collect
  get 'collect_tt/:auth_token/:preview', to: 'tree_test_participants#new', as: :tree_test_collect_preview

  get 'collect_cs/:auth_token', to: 'card_sort_participants#new', as: :card_sort_collect
  get 'collect_cs/:auth_token/:preview', to: 'card_sort_participants#new', as: :card_sort_collect_preview  


  resources :tree_test_reports, only: :show do
    member do 
      get 'login'
      post 'login'
    end
  end

  resources :card_sort_reports, only: :show do
    member do 
      get 'login'
      post 'login'
    end
  end

  get '/admin/password_reset', to: 'admin#password_reset'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "UX Metrics - Online card sorting and tree test studies" %></title>
  <meta name="description" content="<%= "Set up free online card sort and tree test studies in minutes, even if you've never done user research. Research, test and improve your information architecture." %>" />

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_pack_tag "application", "data-turbolinks-track": "reload", async: true %>

  <%= favicon_link_tag asset_pack_path('media/images/favicon.png') %>

  <%= stylesheet_pack_tag "application", "data-turbolinks-track": "reload", media: 'all' %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script async defer data-domain="uxmetrics.com" src="https://analytics.uxmetrics.com/js/index.js"></script>
  <script>
    (function () {
      var s = document.createElement('script');
      s.type = 'text/javascript';
      s.async = true;
      s.src = 'https://app.termly.io/embed.min.js';
      s.id = '06942775-510a-4ef9-a9ee-2404083d70a1';
      s.setAttribute("data-name", "termly-embed-banner");
      var x = document.getElementsByTagName('script')[0];
      x.parentNode.insertBefore(s, x);
    })();
  </script>  

</head>

<body>
  <%= render "shared/navigation" %>
  <%= yield %>
  <%= render "shared/flash" %>
  <%= render "shared/footer" %>
</body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html>
<head>

  <title><%= "#{Rails.configuration.application_name}" %></title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

  <%= favicon_link_tag asset_pack_path('media/images/favicon.png') %>

  <%= stylesheet_pack_tag "application", "data-turbolinks-track": "reload" %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script async defer data-domain="uxmetrics.com" src="https://analytics.uxmetrics.com/js/index.js"></script>
  <script>
    (function () {
      var s = document.createElement('script');
      s.type = 'text/javascript';
      s.async = true;
      s.src = 'https://app.termly.io/embed.min.js';
      s.id = '06942775-510a-4ef9-a9ee-2404083d70a1';
      s.setAttribute("data-name", "termly-embed-banner");
      var x = document.getElementsByTagName('script')[0];
      x.parentNode.insertBefore(s, x);
    })();
  </script> 
  
</head>

<body>
  <%= yield %>
  <%= render "shared/flash" %>
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html class="w-full sm:h-full">
<head>

  <title><%= "#{Rails.configuration.application_name}" %></title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_pack_tag "dashboard", "data-turbolinks-track": "reload" %>

  <%= favicon_link_tag asset_pack_path('media/images/favicon.png') %>

  <%= stylesheet_pack_tag "dashboard", "data-turbolinks-track": "reload" %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script async defer data-domain="uxmetrics.com" src="https://analytics.uxmetrics.com/js/index.js"></script>
  
  <script src="https://js.stripe.com/v3/"></script>
  <script>
    (function () {
      var s = document.createElement('script');
      s.type = 'text/javascript';
      s.async = true;
      s.src = 'https://app.termly.io/embed.min.js';
      s.id = '06942775-510a-4ef9-a9ee-2404083d70a1';
      s.setAttribute("data-name", "termly-embed-banner");
      var x = document.getElementsByTagName('script')[0];
      x.parentNode.insertBefore(s, x);
    })();
  </script> 
  
</head>

<body class="w-full h-full">
  <div class="min-h-screen bg-gray-100">
    <nav x-data="{ open: false }" class="bg-white shadow-sm">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
          <div class="flex">
            <div class="flex-shrink-0 flex items-center">
              <%= link_to image_tag(asset_pack_path("media/images/uxmetrics-logo-full.svg"), size: "163x40"), dashboard_path, class: "block lg:hidden" %>
              <%= link_to image_tag(asset_pack_path("media/images/uxmetrics-logo-full.svg"), size: "163x40"), dashboard_path, class: "hidden lg:block" %>
            </div>
            <div class="hidden sm:ml-6 sm:flex">
              <%= link_to "Card Sorts", card_sorts_path, class:"inline-flex items-center px-1 pt-1 text-sm font-medium leading-5 text-gray-900 focus:outline-none focus:border-purple-700 transition duration-150 ease-in-out" %>
            </div>
            <div class="hidden sm:ml-6 sm:flex">
              <%= link_to "Tree Tests", tree_tests_path, class:"inline-flex items-center px-1 pt-1 text-sm font-medium leading-5 text-gray-900 focus:outline-none focus:border-purple-700 transition duration-150 ease-in-out" %>
            </div>
          </div>
          <div class="hidden sm:ml-6 sm:flex sm:items-center">
            <div class="ml-3 relative">
              <div>
                <div class="hidden sm:ml-6 sm:flex sm:items-center">
                  <div @click.away="open = false" class="ml-3 relative" x-data="{ open: false }">
                    <div>
                      <button @click="open = !open" class="flex text-sm p-2 border-2 border-transparent rounded-full focus:outline-none focus:border-gray-300 transition duration-150 ease-in-out">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <path d="M10.3246 4.31731C10.751 2.5609 13.249 2.5609 13.6754 4.31731C13.9508 5.45193 15.2507 5.99038 16.2478 5.38285C17.7913 4.44239 19.5576 6.2087 18.6172 7.75218C18.0096 8.74925 18.5481 10.0492 19.6827 10.3246C21.4391 10.751 21.4391 13.249 19.6827 13.6754C18.5481 13.9508 18.0096 15.2507 18.6172 16.2478C19.5576 17.7913 17.7913 19.5576 16.2478 18.6172C15.2507 18.0096 13.9508 18.5481 13.6754 19.6827C13.249 21.4391 10.751 21.4391 10.3246 19.6827C10.0492 18.5481 8.74926 18.0096 7.75219 18.6172C6.2087 19.5576 4.44239 17.7913 5.38285 16.2478C5.99038 15.2507 5.45193 13.9508 4.31731 13.6754C2.5609 13.249 2.5609 10.751 4.31731 10.3246C5.45193 10.0492 5.99037 8.74926 5.38285 7.75218C4.44239 6.2087 6.2087 4.44239 7.75219 5.38285C8.74926 5.99037 10.0492 5.45193 10.3246 4.31731Z" stroke="#4A5568" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                          <path d="M15 12C15 13.6569 13.6569 15 12 15C10.3431 15 9 13.6569 9 12C9 10.3431 10.3431 9 12 9C13.6569 9 15 10.3431 15 12Z" stroke="#4A5568" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                      </button>
                    </div>
                    <div x-show="open" x-transition:enter="transition ease-out duration-200" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg">
                      <div class="py-1 rounded-md bg-white shadow-xs">
                        <%= link_to "Account",  account_path, class: "block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out" %>
                        <%= link_to "Logout", logout_path, method: :delete, class: "block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out" %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="-mr-2 flex items-center sm:hidden">
            <button @click="open = !open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
              <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                <path :class="{'hidden': open, 'inline-flex': !open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                <path :class="{'hidden': !open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
      </div>
      <div :class="{'block': open, 'hidden': !open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3">
          <%= link_to "Card Sorts", card_sorts_path, class:"mt-1 block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:outline-none focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300 transition duration-150 ease-in-out"%>
          <%= link_to "Tree Tests", tree_tests_path, class:"mt-1 block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:outline-none focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300 transition duration-150 ease-in-out"%>
        </div>
        <div class="pt-4 pb-3 border-t border-gray-200">
          <%= link_to "Account",  account_path, class: "mt-1 block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100 focus:outline-none focus:text-gray-800 focus:bg-gray-100 transition duration-150 ease-in-out" %>
          <%= link_to "Logout", logout_path, method: :delete, class: "mt-1 block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100 focus:outline-none focus:text-gray-800 focus:bg-gray-100 transition duration-150 ease-in-out" %>
        </div>
      </div>
    </nav>
    <div data-behavior="vue">
      <%= yield %>
    </div>
  </div>
  <footer>
    <div class="border-t border-gray-200 py-12 bg-gray-100">
        <p class="text-base leading-6 text-gray-400 text-center mb-2">
          &copy; 2020-<%= Time.zone.now.strftime("%Y") %> UX Metrics, LLC. All rights reserved.
        </p>
        <p class="text-base leading-6 text-gray-400 text-center">
          Need help? <a href="mailto:support@uxmetrics.com" target="blank" class="text-purple-600">support@uxmetrics.com</a>
        </p>
      </div>
    </div>
  </footer>
  <%= render "shared/flash" %>
</body>
</html>

app/views/layouts/participants.html.erb
<!DOCTYPE html>
<html class="h-full">
<head>

  <title><%= "#{Rails.configuration.application_name}" %></title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_pack_tag "participants", "data-turbolinks-track": "reload" %>

  <%= favicon_link_tag asset_pack_path('media/images/favicon.png') %>

  <%= stylesheet_pack_tag "participants", "data-turbolinks-track": "reload" %>

  <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1.0">

  <script async defer data-domain="uxmetrics.com" src="https://analytics.uxmetrics.com/js/index.js"></script> 
  <script>
    (function () {
      var s = document.createElement('script');
      s.type = 'text/javascript';
      s.async = true;
      s.src = 'https://app.termly.io/embed.min.js';
      s.id = '06942775-510a-4ef9-a9ee-2404083d70a1';
      s.setAttribute("data-name", "termly-embed-banner");
      var x = document.getElementsByTagName('script')[0];
      x.parentNode.insertBefore(s, x);
    })();
  </script> 
  
</head>

<body class="h-full">
  <div class="h-full" data-behavior="vue">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/public_report.html.erb
<!DOCTYPE html>
<html class="w-full sm:h-full">
<head>

  <title><%= "#{Rails.configuration.application_name}" %></title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_pack_tag "dashboard", "data-turbolinks-track": "reload" %>

  <%= favicon_link_tag asset_pack_path('media/images/favicon.png') %>

  <%= stylesheet_pack_tag "dashboard", "data-turbolinks-track": "reload" %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script async defer data-domain="uxmetrics.com" src="https://analytics.uxmetrics.com/js/index.js"></script>  
  <script>
    (function () {
      var s = document.createElement('script');
      s.type = 'text/javascript';
      s.async = true;
      s.src = 'https://app.termly.io/embed.min.js';
      s.id = '06942775-510a-4ef9-a9ee-2404083d70a1';
      s.setAttribute("data-name", "termly-embed-banner");
      var x = document.getElementsByTagName('script')[0];
      x.parentNode.insertBefore(s, x);
    })();
  </script> 
  
</head>

<body class="w-full h-full">
  <div class="min-h-screen bg-gray-100">
    <div data-behavior="vue">
      <%= yield %>
    </div>
  </div>
  <footer>
    <div class="border-t border-gray-200 py-12 bg-gray-100">
        <p class="text-base leading-6 text-gray-400 text-center">
          &copy; 2020-<%= Time.zone.now.strftime("%Y") %> UX Metrics, LLC. All rights reserved.
        </p>
      </div>
    </div>
  </footer>
  <%= render "shared/flash" %>
</body>
</html>